### PR TITLE
Build Fedora 37 docker image

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by akurtakov** [comment]
@fredg02 it looks like there is some magic that needs to be done from webmaster side, right?

**Comment by akurtakov** [comment]
@mbarbero maybe you can help?

**Comment by akurtakov** [comment]
Any help what I'm missing here is more than appreciated.

**Comment by mbarbero** [comment]
I'm afraid I don't have a hint at why this fails.

**Comment by akurtakov** [comment]
Could it be that docker.io indentifier has to be created first before script can push?

**Comment by mbarbero** [comment]
> Could it be that docker.io indentifier has to be created first before script can push?

no, tags can be created by the user pushing

**Comment by akurtakov** [comment]
So the error is https://ci.eclipse.org/cbi/job/dockerfiles/job/PR-27/13/execution/node/155/log/ : 
failed to solve: eclipsecbi/fedora:37: docker.io/eclipsecbi/fedora:37: not found 
Where/what is supposed to create this one?

**Comment by akurtakov** [comment]
I think I figured it . Have to submit it in two steps as the second step requires the image being pushed to docker.io.

**Pull request merged**
