### PR TITLE
WIP - Add Ubuntu 22.04 LTS

### PR DESCRIPTION
**Pull request by fredg02**

### CODE REVIEW

**Comment by mbarbero** [comment]
FYI, PR can be marked as "draft". https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft

**Comment by heurtematte** [comment]
@fredg02 I just did a rebase on master. CI had been in failed state for the last few month.

**Comment by fredg02** [comment]
@heurtematte is there a good reason to keep building Ubuntu 18.04 base images?

**Comment by heurtematte** [comment]
> @heurtematte is there a good reason to keep building Ubuntu 18.04 base images?

Do we have projects that use it? If not we can drop it.

NOTE: Standard support ended last June 2023, but EOL is 2028.

**Comment by fredg02** [comment]
> Do we have projects that use it? If not we can drop it.

We will need to check. We should encourage everyone to migrate to 22.04 .

**Comment by fredg02** [comment]
I went ahead and removed 18.04 again. The image is still there, but we won't build it anymore. I will create a separate task issue to track if/where 18.04 images are still used.

**Pull request merged**
