### PR TITLE
Add Fedora 30.

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by akurtakov** [comment]
Would you please push to dockerhub so we can start using it?

**Comment by mbarbero** [comment]
in progress https://ci.eclipse.org/cbi/job/dockerfiles/job/master/68/console

**Comment by mbarbero** [comment]
(I've added a webhook for automatically triggering build on new commit)

**Comment by mbarbero** [comment]
FYI, I also had to do https://github.com/eclipse-cbi/dockerfiles/commit/2ac00b370d05557cc71a7cfe13731bbebfa635af

**Comment by akurtakov** [comment]
https://hub.docker.com/r/eclipsecbi/fedora-gtk3-mutter/tags still doesn't list fedora 30

**Comment by mbarbero** [comment]
> https://hub.docker.com/r/eclipsecbi/fedora-gtk3-mutter/tags still doesn't list fedora 30

Fixed.

**Comment by akurtakov** [comment]
Are you sure that the proper tag is pushed ? It seems to be Fedora 28 :
STEP 1: FROM eclipsecbi/fedora-gtk3-mutter:30-gtk3.24
STEP 2: USER 0
STEP 3: RUN cat /etc/os-release
NAME=Fedora
VERSION="28 (Twenty Eight)"
ID=fedora
VERSION_ID=28
VERSION_CODENAME=""
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Twenty Eight)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
STEP 4: RUN dnf update && dnf -y install 	java-openjdk maven

**Comment by mbarbero** [comment]
Weird. I'm still investigating.

**Comment by akurtakov** [comment]
Any progress here?

**Comment by mbarbero** [comment]
see issue #10

**Pull request merged**
